apiVersion: v1
kind: BuildConfig
metadata:
  name: simple-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: simple-test:latest
  source:
    git:
      ref: very-simple-with-internet
      uri: https://github.com/chmouel/simple-dockerfile
    type: Git
  strategy:
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: registry.access.redhat.com/openshift3/python-33-rhel7:latest
      type: ImageChange
