apiVersion: v1
kind: BuildConfig
metadata:
  name: simpletest
spec:
  output:
    to:
      kind: ImageStreamTag
      name: simpletest:latest
  source:
    git:
      ref: very-simple
      uri: https://github.com/chmouel/simple-dockerfile
    type: Git
  strategy:
    type: Docker
