apiVersion: v1
kind: BuildConfig
metadata:
  name: simple-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: simple-test:latest
  source:
    git:
      ref: master
      uri: https://github.com/chmouel/simple-dockerfile
    type: Git
  strategy:
    type: Docker
  triggers:
    - generic:
        secret: 7147201e200ea2da
      type: Generic
    - github:
        secret: 9e7d74830de47006
      type: GitHub
    - imageChange:
        lastTriggeredImageID: registry.access.redhat.com/openshift3/python-33-rhel7:latest
      type: ImageChange
