apiVersion: v1
kind: DeploymentConfig
metadata:
  name: simple-test-db
spec:
  replicas: 1
  selector:
    name: simple-database
  strategy:
    type: Recreate
  triggers:
    - type: ConfigChange
  template:
    metadata:
      labels:
        name: simple-database
    spec:
      containers:
        - image: openshift3/mysql-55-rhel7:latest
          imagePullPolicy: Always
          name: simple-test-db
          ports:
            - containerPort: 3306
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          env:
          - name: MYSQL_USER
            value: chmouel
          - name: MYSQL_PASSWORD
            value: chmouel
          - name: MYSQL_DATABASE
            value: chmouel
      dnsPolicy: ClusterFirst
      restartPolicy: Always
